//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XB1ControllerBatteryIndicator.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XB1ControllerBatteryIndicator.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string BatteryLevel_Empty {
            get {
                return ResourceManager.GetString("BatteryLevel_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string BatteryLevel_Full {
            get {
                return ResourceManager.GetString("BatteryLevel_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string BatteryLevel_Low {
            get {
                return ResourceManager.GetString("BatteryLevel_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string BatteryLevel_Medium {
            get {
                return ResourceManager.GetString("BatteryLevel_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string ContextMenu_AutoStart {
            get {
                return ResourceManager.GetString("ContextMenu_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ContextMenu_Exit {
            get {
                return ResourceManager.GetString("ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ContextMenu_Language {
            get {
                return ResourceManager.GetString("ContextMenu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty battery warning sound.
        /// </summary>
        public static string ContextMenu_LowBatteryWarningSound {
            get {
                return ResourceManager.GetString("ContextMenu_LowBatteryWarningSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ContextMenu_LowBatteryWarningSound_Enabled {
            get {
                return ResourceManager.GetString("ContextMenu_LowBatteryWarningSound_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat on loop.
        /// </summary>
        public static string ContextMenu_LowBatteryWarningSound_Loop_Enabled {
            get {
                return ResourceManager.GetString("ContextMenu_LowBatteryWarningSound_Loop_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Settings....
        /// </summary>
        public static string ContextMenu_PopupSettings {
            get {
                return ResourceManager.GetString("ContextMenu_PopupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Popup on Guide.
        /// </summary>
        public static string ContextMenu_ShowPopupOnGuide {
            get {
                return ResourceManager.GetString("ContextMenu_ShowPopupOnGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Popup on low battery.
        /// </summary>
        public static string ContextMenu_ShowPopupOnLowBattery {
            get {
                return ResourceManager.GetString("ContextMenu_ShowPopupOnLowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toast on low battery.
        /// </summary>
        public static string ContextMenu_ShowToastOnLowBattery {
            get {
                return ResourceManager.GetString("ContextMenu_ShowToastOnLowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new version on start.
        /// </summary>
        public static string ContextMenu_UpdateCheck {
            get {
                return ResourceManager.GetString("ContextMenu_UpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        public static string ControllerIndex_Four {
            get {
                return ResourceManager.GetString("ControllerIndex_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string ControllerIndex_One {
            get {
                return ResourceManager.GetString("ControllerIndex_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string ControllerIndex_Three {
            get {
                return ResourceManager.GetString("ControllerIndex_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string ControllerIndex_Two {
            get {
                return ResourceManager.GetString("ControllerIndex_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of {0} is available. Do you want to open the Homepage?.
        /// </summary>
        public static string NewVersionAvailable_Body {
            get {
                return ResourceManager.GetString("NewVersionAvailable_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string NewVersionAvailable_Title {
            get {
                return ResourceManager.GetString("NewVersionAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery level: {0}.
        /// </summary>
        public static string Popup_BatteryLevel {
            get {
                return ResourceManager.GetString("Popup_BatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0}.
        /// </summary>
        public static string Popup_ControllerName {
            get {
                return ResourceManager.GetString("Popup_ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background:.
        /// </summary>
        public static string PopupSettings_Background {
            get {
                return ResourceManager.GetString("PopupSettings_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PopupSettings_Cancel {
            get {
                return ResourceManager.GetString("PopupSettings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string PopupSettings_Colors {
            get {
                return ResourceManager.GetString("PopupSettings_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display:.
        /// </summary>
        public static string PopupSettings_DisplayDuration {
            get {
                return ResourceManager.GetString("PopupSettings_DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string PopupSettings_Font {
            get {
                return ResourceManager.GetString("PopupSettings_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string PopupSettings_FontName {
            get {
                return ResourceManager.GetString("PopupSettings_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string PopupSettings_FontSize {
            get {
                return ResourceManager.GetString("PopupSettings_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground:.
        /// </summary>
        public static string PopupSettings_Foreground {
            get {
                return ResourceManager.GetString("PopupSettings_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string PopupSettings_Height {
            get {
                return ResourceManager.GetString("PopupSettings_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string PopupSettings_Percent {
            get {
                return ResourceManager.GetString("PopupSettings_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        public static string PopupSettings_Pixel {
            get {
                return ResourceManager.GetString("PopupSettings_Pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positioning.
        /// </summary>
        public static string PopupSettings_Positioning {
            get {
                return ResourceManager.GetString("PopupSettings_Positioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PopupSettings_Save {
            get {
                return ResourceManager.GetString("PopupSettings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string PopupSettings_Seconds {
            get {
                return ResourceManager.GetString("PopupSettings_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string PopupSettings_Time {
            get {
                return ResourceManager.GetString("PopupSettings_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string PopupSettings_Width {
            get {
                return ResourceManager.GetString("PopupSettings_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string PopupSettings_X {
            get {
                return ResourceManager.GetString("PopupSettings_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string PopupSettings_Y {
            get {
                return ResourceManager.GetString("PopupSettings_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut up!.
        /// </summary>
        public static string Toast_Dismiss {
            get {
                return ResourceManager.GetString("Toast_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery of controller {0} is (almost) empty..
        /// </summary>
        public static string Toast_Text {
            get {
                return ResourceManager.GetString("Toast_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click on the Button to stop the reappearing of this warning.).
        /// </summary>
        public static string Toast_Text2 {
            get {
                return ResourceManager.GetString("Toast_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} low battery warning.
        /// </summary>
        public static string Toast_Title {
            get {
                return ResourceManager.GetString("Toast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No controller detected.
        /// </summary>
        public static string ToolTip_NoController {
            get {
                return ResourceManager.GetString("ToolTip_NoController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} - Unknown.
        /// </summary>
        public static string ToolTip_Unknown {
            get {
                return ResourceManager.GetString("ToolTip_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} - Found but still waiting for battery data....
        /// </summary>
        public static string ToolTip_WaitingForData {
            get {
                return ResourceManager.GetString("ToolTip_WaitingForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} - Wired.
        /// </summary>
        public static string ToolTip_Wired {
            get {
                return ResourceManager.GetString("ToolTip_Wired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0} - Battery level: {1}.
        /// </summary>
        public static string ToolTip_Wireless {
            get {
                return ResourceManager.GetString("ToolTip_Wireless", resourceCulture);
            }
        }
    }
}
