//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XB1ControllerBatteryIndicator.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XB1ControllerBatteryIndicator.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string About_Group {
            get {
                return ResourceManager.GetString("About_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty ähnelt.
        /// </summary>
        public static string BatteryLevel_Empty {
            get {
                return ResourceManager.GetString("BatteryLevel_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full ähnelt.
        /// </summary>
        public static string BatteryLevel_Full {
            get {
                return ResourceManager.GetString("BatteryLevel_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Low ähnelt.
        /// </summary>
        public static string BatteryLevel_Low {
            get {
                return ResourceManager.GetString("BatteryLevel_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium ähnelt.
        /// </summary>
        public static string BatteryLevel_Medium {
            get {
                return ResourceManager.GetString("BatteryLevel_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start with Windows ähnelt.
        /// </summary>
        public static string ContextMenu_AutoStart {
            get {
                return ResourceManager.GetString("ContextMenu_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displayed Controller states ähnelt.
        /// </summary>
        public static string ContextMenu_DisplayedIcons {
            get {
                return ResourceManager.GetString("ContextMenu_DisplayedIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string ContextMenu_Exit {
            get {
                return ResourceManager.GetString("ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string ContextMenu_Language {
            get {
                return ResourceManager.GetString("ContextMenu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty battery warning sound ähnelt.
        /// </summary>
        public static string ContextMenu_LowBatteryWarningSound {
            get {
                return ResourceManager.GetString("ContextMenu_LowBatteryWarningSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
        /// </summary>
        public static string ContextMenu_LowBatteryWarningSound_Enabled {
            get {
                return ResourceManager.GetString("ContextMenu_LowBatteryWarningSound_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat on loop ähnelt.
        /// </summary>
        public static string ContextMenu_LowBatteryWarningSound_Loop_Enabled {
            get {
                return ResourceManager.GetString("ContextMenu_LowBatteryWarningSound_Loop_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Also check for minor updates (new languages added) ähnelt.
        /// </summary>
        public static string ContextMenu_MinorUpdateCheck {
            get {
                return ResourceManager.GetString("ContextMenu_MinorUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications ähnelt.
        /// </summary>
        public static string ContextMenu_Notifications {
            get {
                return ResourceManager.GetString("ContextMenu_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Popup Settings... ähnelt.
        /// </summary>
        public static string ContextMenu_PopupSettings {
            get {
                return ResourceManager.GetString("ContextMenu_PopupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Popup on pressing XBox button ähnelt.
        /// </summary>
        public static string ContextMenu_ShowPopupOnGuide {
            get {
                return ResourceManager.GetString("ContextMenu_ShowPopupOnGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Popup on low battery ähnelt.
        /// </summary>
        public static string ContextMenu_ShowPopupOnLowBattery {
            get {
                return ResourceManager.GetString("ContextMenu_ShowPopupOnLowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Toast on low battery ähnelt.
        /// </summary>
        public static string ContextMenu_ShowToastOnLowBattery {
            get {
                return ResourceManager.GetString("ContextMenu_ShowToastOnLowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wired controllers ähnelt.
        /// </summary>
        public static string ContextMenu_ShowWiredControllers {
            get {
                return ResourceManager.GetString("ContextMenu_ShowWiredControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wireless controllers battery level ähnelt.
        /// </summary>
        public static string ContextMenu_ShowWirelessControllersWithKnownBatteryLevel {
            get {
                return ResourceManager.GetString("ContextMenu_ShowWirelessControllersWithKnownBatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wireless controllers with unknown battery level ähnelt.
        /// </summary>
        public static string ContextMenu_ShowWirelessControllersWithUnknownBatteryLevel {
            get {
                return ResourceManager.GetString("ContextMenu_ShowWirelessControllersWithUnknownBatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for new version on start ähnelt.
        /// </summary>
        public static string ContextMenu_UpdateCheck {
            get {
                return ResourceManager.GetString("ContextMenu_UpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update check ähnelt.
        /// </summary>
        public static string ContextMenu_UpdateCheckHeader {
            get {
                return ResourceManager.GetString("ContextMenu_UpdateCheckHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Four ähnelt.
        /// </summary>
        public static string ControllerIndex_Four {
            get {
                return ResourceManager.GetString("ControllerIndex_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One ähnelt.
        /// </summary>
        public static string ControllerIndex_One {
            get {
                return ResourceManager.GetString("ControllerIndex_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Three ähnelt.
        /// </summary>
        public static string ControllerIndex_Three {
            get {
                return ResourceManager.GetString("ControllerIndex_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two ähnelt.
        /// </summary>
        public static string ControllerIndex_Two {
            get {
                return ResourceManager.GetString("ControllerIndex_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new minor update for {0} is available (new languages added). Do you want to open the homepage? ähnelt.
        /// </summary>
        public static string NewMinorVersionAvailable_Body {
            get {
                return ResourceManager.GetString("NewMinorVersionAvailable_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new version of {0} is available. Do you want to open the Homepage? ähnelt.
        /// </summary>
        public static string NewVersionAvailable_Body {
            get {
                return ResourceManager.GetString("NewVersionAvailable_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New version available ähnelt.
        /// </summary>
        public static string NewVersionAvailable_Title {
            get {
                return ResourceManager.GetString("NewVersionAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery level: {0} ähnelt.
        /// </summary>
        public static string Popup_BatteryLevel {
            get {
                return ResourceManager.GetString("Popup_BatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller {0} ähnelt.
        /// </summary>
        public static string Popup_ControllerName {
            get {
                return ResourceManager.GetString("Popup_ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background: ähnelt.
        /// </summary>
        public static string PopupSettings_Background {
            get {
                return ResourceManager.GetString("PopupSettings_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string PopupSettings_Cancel {
            get {
                return ResourceManager.GetString("PopupSettings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colors ähnelt.
        /// </summary>
        public static string PopupSettings_Colors {
            get {
                return ResourceManager.GetString("PopupSettings_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display for: ähnelt.
        /// </summary>
        public static string PopupSettings_DisplayDuration {
            get {
                return ResourceManager.GetString("PopupSettings_DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font ähnelt.
        /// </summary>
        public static string PopupSettings_Font {
            get {
                return ResourceManager.GetString("PopupSettings_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bold: ähnelt.
        /// </summary>
        public static string PopupSettings_FontBold {
            get {
                return ResourceManager.GetString("PopupSettings_FontBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Italic: ähnelt.
        /// </summary>
        public static string PopupSettings_FontItalic {
            get {
                return ResourceManager.GetString("PopupSettings_FontItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string PopupSettings_FontName {
            get {
                return ResourceManager.GetString("PopupSettings_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size: ähnelt.
        /// </summary>
        public static string PopupSettings_FontSize {
            get {
                return ResourceManager.GetString("PopupSettings_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Underline: ähnelt.
        /// </summary>
        public static string PopupSettings_FontUnderline {
            get {
                return ResourceManager.GetString("PopupSettings_FontUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foreground: ähnelt.
        /// </summary>
        public static string PopupSettings_Foreground {
            get {
                return ResourceManager.GetString("PopupSettings_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height: ähnelt.
        /// </summary>
        public static string PopupSettings_Height {
            get {
                return ResourceManager.GetString("PopupSettings_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % ähnelt.
        /// </summary>
        public static string PopupSettings_Percent {
            get {
                return ResourceManager.GetString("PopupSettings_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die px ähnelt.
        /// </summary>
        public static string PopupSettings_Pixel {
            get {
                return ResourceManager.GetString("PopupSettings_Pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positioning ähnelt.
        /// </summary>
        public static string PopupSettings_Positioning {
            get {
                return ResourceManager.GetString("PopupSettings_Positioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string PopupSettings_Save {
            get {
                return ResourceManager.GetString("PopupSettings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sec ähnelt.
        /// </summary>
        public static string PopupSettings_Seconds {
            get {
                return ResourceManager.GetString("PopupSettings_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        public static string PopupSettings_Time {
            get {
                return ResourceManager.GetString("PopupSettings_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery Level Popup Settings ähnelt.
        /// </summary>
        public static string PopupSettings_Title {
            get {
                return ResourceManager.GetString("PopupSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width: ähnelt.
        /// </summary>
        public static string PopupSettings_Width {
            get {
                return ResourceManager.GetString("PopupSettings_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X: ähnelt.
        /// </summary>
        public static string PopupSettings_X {
            get {
                return ResourceManager.GetString("PopupSettings_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y: ähnelt.
        /// </summary>
        public static string PopupSettings_Y {
            get {
                return ResourceManager.GetString("PopupSettings_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shut up! ähnelt.
        /// </summary>
        public static string Toast_Dismiss {
            get {
                return ResourceManager.GetString("Toast_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery of controller {0} is (almost) empty. ähnelt.
        /// </summary>
        public static string Toast_Text {
            get {
                return ResourceManager.GetString("Toast_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Click on the Button to stop the reappearing of this warning.) ähnelt.
        /// </summary>
        public static string Toast_Text2 {
            get {
                return ResourceManager.GetString("Toast_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller {0} low battery warning ähnelt.
        /// </summary>
        public static string Toast_Title {
            get {
                return ResourceManager.GetString("Toast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No controller detected ähnelt.
        /// </summary>
        public static string ToolTip_NoController {
            get {
                return ResourceManager.GetString("ToolTip_NoController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller {0} - Unknown ähnelt.
        /// </summary>
        public static string ToolTip_Unknown {
            get {
                return ResourceManager.GetString("ToolTip_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller {0} - Found but still waiting for battery data... ähnelt.
        /// </summary>
        public static string ToolTip_WaitingForData {
            get {
                return ResourceManager.GetString("ToolTip_WaitingForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller {0} - Wired ähnelt.
        /// </summary>
        public static string ToolTip_Wired {
            get {
                return ResourceManager.GetString("ToolTip_Wired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller {0} - Battery level: {1} ähnelt.
        /// </summary>
        public static string ToolTip_Wireless {
            get {
                return ResourceManager.GetString("ToolTip_Wireless", resourceCulture);
            }
        }
    }
}
